version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
 
before_build:
  - cmd: dotnet restore ./src/Nager.Country.sln

build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet build ./src/Nager.Country.sln --configuration Release

test_script:
  - cmd: dotnet test ./src/Nager.Country.UnitTest/Nager.Country.UnitTest.csproj --logger:AppVeyor

artifacts:  
  - path: Nager.Country.[0-9]{1}.[0-9]{1}.[0-9]{1}.nupkg
    name: nugetpackage
  
deploy:
  provider: NuGet
  api_key:
    secure: yd+EICeWOnPIZ5abqix5pClg/jJFFwkjC2zICq/WFTjuFy5miezzZG4eY8DGeljN
  artifact: nugetpackage