version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
 
before_build:
  - cmd: dotnet restore ./src/Nager.Country.sln

build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet build ./src/Nager.Country.sln --configuration Release

test_script:
  - cmd: dotnet test ./src/Nager.Country.UnitTest/Nager.Country.UnitTest.csproj --logger:AppVeyor

artifacts:  
  - path: '**\*.nupkg'
    name: nugetpackage
  
deploy:
  provider: NuGet
  api_key:
    secure: +JijYO/6j0Jr4LhgXa20PgLIQoBqegkzawUE7CsSzskmexCbNkv+N5Bwu3r6HTsN
  artifact: nugetpackage
